### ISSUE TITLE
Consider changing NOMAD_ADDRESS to NOMAD_ADDR

### ISSUE THREAD

**Issue by axsuul** [dmaes/nomad-logger#2]
Mainly since the Nomad CLI uses `NOMAD_ADDR` as well as most tooling in the ecosystem: https://www.nomadproject.io/docs/commands#nomad_addr

...or maybe we can support both `NOMAD_ADDRESS` and `NOMAD_ADDR`? 

Thanks for developing a great tool!

**Comment by dmaes** [comment]
Using `NOMAD_ADDR` does indeed make more sense, will change it.
